import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const coffeeShops = [
  {
    name: 'Kopi Joss Purwokerto',
    slug: 'kopi-joss-purwokerto',
    city: 'Banyumas',
    district: 'Purwokerto Selatan',
    address: 'Jl. Mgr. Soegijopranoto No. 21, Purwokerto',
    googleMapsUrl: 'https://maps.google.com/?q=Kopi+Joss+Purwokerto',
    instagramUrl: 'https://instagram.com/kopijospurwokerto',
    phone: '0812-3456-7890',
    description: 'Kopi Joss adalah kedai kopi legendaris di Purwokerto dengan suasana klasik yang cocok untuk bekerja. WiFi cepat dan banyak colokan.',
    priceRange: 'budget',
    priceLabel: '< Rp20K',
    wifiScore: 8,
    outletScore: 9,
    comfortScore: 7,
    noiseScore: 6,
    meetingScore: 5,
    seatingScore: 7,
    openingHours: '07:00 - 22:00',
    founderScore: 7.2,
    featured: true,
    status: 'approved',
    amenities: ['wifi', 'outlet', 'ac', 'quiet'],
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800',
  },
  {
    name: 'Seblak & Kopi Cabbin',
    slug: 'seblak-kopi-cabbin-purwokerto',
    city: 'Banyumas',
    district: 'Purwokerto Timur',
    address: 'Jl. Overste ISKandar No. 15, Purwokerto',
    description: 'Tempat unik dengan kombinasi seblak dan kopi. Suasana modern dengan meja panjang yang cocok untuk kerja bareng.',
    priceRange: 'moderate',
    priceLabel: 'Rp20K–40K',
    wifiScore: 9,
    outletScore: 8,
    comfortScore: 8,
    noiseScore: 5,
    meetingScore: 7,
    seatingScore: 8,
    openingHours: '10:00 - 23:00',
    founderScore: 7.8,
    featured: false,
    status: 'approved',
    amenities: ['wifi', 'outlet', 'meeting', 'ac'],
    imageUrl: 'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?w=800',
  },
  {
    name: 'Dewandtu Coffee',
    slug: 'dewandtu-coffee-purwokerto',
    city: 'Banyumas',
    district: 'Purwokerto Utara',
    address: 'Jl. Tersakyatan No. 8, Purwokerto',
    description: 'Coffee shop minimalis dengan nuansa industrial. Favorit para developer dan freelancer lokal.',
    priceRange: 'moderate',
    priceLabel: 'Rp20K–40K',
    wifiScore: 9,
    outletScore: 9,
    comfortScore: 9,
    noiseScore: 8,
    meetingScore: 6,
    seatingScore: 7,
    openingHours: '08:00 - 21:00',
    founderScore: 8.4,
    featured: true,
    status: 'approved',
    amenities: ['wifi', 'outlet', 'quiet', 'ac'],
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
  },
  {
    name: 'Kedai Kopi Sokanadi',
    slug: 'kedai-kopi-sokanadi-purwokerto',
    city: 'Banyumas',
    district: 'Purwokerto Barat',
    address: 'Jl. Sokanadi No. 1, Purwokerto',
    description: 'Kedai kopi klasik dengan pilihan kopi tradisional dan modern. Tempat tenang untuk membaca dan bekerja.',
    priceRange: 'budget',
    priceLabel: '< Rp20K',
    wifiScore: 7,
    outletScore: 6,
    comfortScore: 7,
    noiseScore: 8,
    meetingScore: 4,
    seatingScore: 6,
    openingHours: '06:30 - 21:00',
    founderScore: 6.5,
    featured: false,
    status: 'approved',
    amenities: ['wifi', 'quiet', 'outdoor'],
    imageUrl: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800',
  },
  {
    name: 'Ruang Tinggal Coffee',
    slug: 'ruang-tinggal-coffee-purwokerto',
    city: 'Banyumas',
    district: 'Purwokerto Selatan',
    address: 'Jl. Sudagaran No. 12, Purwokerto',
    description: 'Coffee shop dengan konsep living room. Nyaman untuk kerja santai dan meeting informal.',
    priceRange: 'moderate',
    priceLabel: 'Rp20K–40K',
    wifiScore: 8,
    outletScore: 8,
    comfortScore: 9,
    noiseScore: 7,
    meetingScore: 8,
    seatingScore: 8,
    openingHours: '09:00 - 22:00',
    founderScore: 8.0,
    featured: true,
    status: 'approved',
    amenities: ['wifi', 'outlet', 'meeting', 'ac', 'quiet'],
    imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800',
  },
  {
    name: "Kopi Teto'l Purbalingga",
    slug: 'kopi-tetol-purbalingga',
    city: 'Purbalingga',
    district: 'Purbalingga',
    address: 'Jl. Tentara Pelajar No. 8, Purbalingga',
    description: 'Kedai kopi lokal dengan suasana asri. Parkiran luas dan cocok untuk meeting outdoor.',
    priceRange: 'budget',
    priceLabel: '< Rp20K',
    wifiScore: 7,
    outletScore: 5,
    comfortScore: 7,
    noiseScore: 7,
    meetingScore: 6,
    seatingScore: 7,
    openingHours: '07:00 - 21:00',
    founderScore: 6.4,
    featured: false,
    status: 'approved',
    amenities: ['wifi', 'outdoor', 'parking'],
    imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800',
  },
  {
    name: 'Kedai 89 Purbalingga',
    slug: 'kedai-89-purbalingga',
    city: 'Purbalingga',
    district: 'Purbalingga',
    address: 'Jl. Achmad Yani No. 89, Purbalingga',
    description: 'Coffee shop modern dengan interior industrial. WiFi kenceng dan cocok buat ngoding.',
    priceRange: 'moderate',
    priceLabel: 'Rp20K–40K',
    wifiScore: 9,
    outletScore: 9,
    comfortScore: 8,
    noiseScore: 6,
    meetingScore: 7,
    seatingScore: 7,
    openingHours: '10:00 - 22:00',
    founderScore: 7.9,
    featured: true,
    status: 'approved',
    amenities: ['wifi', 'outlet', 'ac', 'meeting'],
    imageUrl: 'https://images.unsplash.com/photo-1498804103079-a6351b050096?w=800',
  },
  {
    name: 'Warung Kopi Mantep',
    slug: 'warung-kopi-mantep-banjarnegara',
    city: 'Banjarnegara',
    district: 'Banjarnegara',
    address: 'Jl. Letjend Suparmo No. 45, Banjarnegara',
    description: 'Tempat nongkrong lokal dengan kopi arabika Banjarnegara. Suasana nyaman dan terjangkau.',
    priceRange: 'budget',
    priceLabel: '< Rp20K',
    wifiScore: 6,
    outletScore: 5,
    comfortScore: 6,
    noiseScore: 7,
    meetingScore: 4,
    seatingScore: 6,
    openingHours: '07:00 - 20:00',
    founderScore: 5.6,
    featured: false,
    status: 'approved',
    amenities: ['wifi', 'outdoor'],
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800',
  },
  {
    name: 'Omah Kopi Dieng',
    slug: 'omah-kopi-dieng-banjarnegara',
    city: 'Banjarnegara',
    district: 'Banjarmangu',
    address: 'Jl. Raya Dieng No. 1, Banjarmangu, Banjarnegara',
    description: 'Coffee shop dengan pemandangan Gunung Dieng. Cocok untuk yang butuh inspirasi segar.',
    priceRange: 'moderate',
    priceLabel: 'Rp20K–40K',
    wifiScore: 7,
    outletScore: 6,
    comfortScore: 8,
    noiseScore: 9,
    meetingScore: 5,
    seatingScore: 8,
    openingHours: '08:00 - 20:00',
    founderScore: 7.2,
    featured: true,
    status: 'approved',
    amenities: ['wifi', 'outdoor', 'quiet', 'ac'],
    imageUrl: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800',
  },
  {
    name: 'Kedai Kopi Bilingual',
    slug: 'kedai-kopi-bilingual-cilacap',
    city: 'Cilacap',
    district: 'Cilacap Selatan',
    address: 'Jl. Gatot Subroto No. 32, Cilacap',
    description: 'Coffee shop modern di jantung Cilacap. AC dingin dan WiFi stabil.',
    priceRange: 'moderate',
    priceLabel: 'Rp20K–40K',
    wifiScore: 8,
    outletScore: 8,
    comfortScore: 8,
    noiseScore: 6,
    meetingScore: 8,
    seatingScore: 7,
    openingHours: '10:00 - 22:00',
    founderScore: 7.7,
    featured: false,
    status: 'approved',
    amenities: ['wifi', 'outlet', 'ac', 'meeting'],
    imageUrl: 'https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=800',
  },
  {
    name: 'Java Splash Coffee',
    slug: 'java-splash-coffee-cilacap',
    city: 'Cilacap',
    district: 'Cilacap Utara',
    address: 'Jl. Ahmad Yani No. 78, Cilacap',
    description: 'Coffee shop dengan nuansa vintage. Tempat asyik untuk workation.',
    priceRange: 'moderate',
    priceLabel: 'Rp20K–40K',
    wifiScore: 8,
    outletScore: 7,
    comfortScore: 7,
    noiseScore: 7,
    meetingScore: 6,
    seatingScore: 7,
    openingHours: '08:00 - 21:00',
    founderScore: 7.1,
    featured: false,
    status: 'approved',
    amenities: ['wifi', 'outlet', 'ac', 'quiet'],
    imageUrl: 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=800',
  },
  {
    name: 'Kopi Kebumen',
    slug: 'kopi-kebumen-kebumen',
    city: 'Kebumen',
    district: 'Kebumen',
    address: 'Jl. Veteran No. 15, Kebumen',
    description: 'Kedai kopi legendaris di Kebumen. Harga mahasiswa banget.',
    priceRange: 'budget',
    priceLabel: '< Rp20K',
    wifiScore: 6,
    outletScore: 5,
    comfortScore: 6,
    noiseScore: 6,
    meetingScore: 3,
    seatingScore: 5,
    openingHours: '06:00 - 20:00',
    founderScore: 5.1,
    featured: false,
    status: 'approved',
    amenities: ['wifi', 'outdoor'],
    imageUrl: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800',
  },
  {
    name: 'Seduh Kopi Kebumen',
    slug: 'seduh-kopi-kebumen',
    city: 'Kebumen',
    district: 'Kebumen',
    address: 'Jl. Pangandaran No. 8, Kebumen',
    description: 'Coffee shop minimalis dengan kopi single origin Kebumen. Tempat tenang untuk bekerja.',
    priceRange: 'moderate',
    priceLabel: 'Rp20K–40K',
    wifiScore: 8,
    outletScore: 8,
    comfortScore: 8,
    noiseScore: 8,
    meetingScore: 5,
    seatingScore: 7,
    openingHours: '09:00 - 21:00',
    founderScore: 7.6,
    featured: true,
    status: 'approved',
    amenities: ['wifi', 'outlet', 'quiet', 'ac'],
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
  },
  {
    name: 'Brewok Coffee House',
    slug: 'brewok-coffee-house-purwokerto',
    city: 'Banyumas',
    district: 'Purwokerto Timur',
    address: 'Jl. Suparto No. 5, Purwokerto',
    description: 'Coffee house dengan konsep modern. Roastery dan cafe dalam satu tempat.',
    priceRange: 'premium',
    priceLabel: '> Rp40K',
    wifiScore: 9,
    outletScore: 9,
    comfortScore: 9,
    noiseScore: 8,
    meetingScore: 9,
    seatingScore: 9,
    openingHours: '07:00 - 23:00',
    founderScore: 9.0,
    featured: true,
    status: 'approved',
    amenities: ['wifi', 'outlet', 'ac', 'meeting', 'quiet', 'parking'],
    imageUrl: 'https://images.unsplash.com/photo-1445116572660-236099ec97a0?w=800',
  },
  {
    name: 'Tuku Kopi Cilacap',
    slug: 'tuku-kopi-cilacap',
    city: 'Cilacap',
    district: 'Cilacap Barat',
    address: 'Jl. Sungai Lukito No. 12, Cilacap',
    description: 'Coffee shop baru dengan suasana cozy. Tempat favorit freelance designers.',
    priceRange: 'moderate',
    priceLabel: 'Rp20K–40K',
    wifiScore: 9,
    outletScore: 8,
    comfortScore: 9,
    noiseScore: 7,
    meetingScore: 7,
    seatingScore: 8,
    openingHours: '10:00 - 22:00',
    founderScore: 8.2,
    featured: false,
    status: 'approved',
    amenities: ['wifi', 'outlet', 'ac', 'meeting'],
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800',
  },
];

async function main() {
  console.log('Starting seed...');

  // Clear existing data
  await prisma.lead.deleteMany();
  await prisma.submission.deleteMany();
  await prisma.coffeeShop.deleteMany();

  console.log('Cleared existing data');

  // Seed coffee shops
  for (const shop of coffeeShops) {
    await prisma.coffeeShop.create({
      data: shop,
    });
    console.log(`Created: ${shop.name}`);
  }

  console.log(`\nSeeded ${coffeeShops.length} coffee shops`);

  // Create sample leads
  const shops = await prisma.coffeeShop.findMany({ take: 5 });
  const sampleLeads = [
    {
      coffeeShopId: shops[0].id,
      name: 'Ahmad Rizki',
      email: 'ahmad@email.com',
      phone: '0812-3456-7890',
      intent: 'work_space',
      message: 'Mau tanya soal work space untuk 1 orang, bisa daily pass?',
      status: 'new',
    },
    {
      coffeeShopId: shops[1].id,
      name: 'Diana Putri',
      email: 'diana@gmail.com',
      phone: '0857-9876-5432',
      intent: 'meeting',
      message: 'Butuh tempat meeting untuk 5 orang, apakah ada private room?',
      status: 'contacted',
    },
    {
      coffeeShopId: shops[2].id,
      name: 'Budi Santoso',
      email: 'budi@startup.io',
      intent: 'event',
      message: 'Interested untuk hosting workshop coding untuk 20 orang.',
      status: 'qualified',
    },
  ];

  for (const lead of sampleLeads) {
    await prisma.lead.create({ data: lead });
    console.log(`Created lead: ${lead.name}`);
  }

  console.log('\nSeed completed!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
